# Generated by Django 4.2.3 on 2023-07-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiels', '0002_materiel_sous_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiel',
            name='en_panne',
            field=models.BooleanField(default=False),
        ),
    ]
